"""
This type stub file was generated by pyright.
"""

from collections import deque
from .base import Clipboard, ClipboardData

__all__ = ["InMemoryClipboard"]
class InMemoryClipboard(Clipboard):
    """
    Default clipboard implementation.
    Just keep the data in memory.

    This implements a kill-ring, for Emacs mode.
    """
    def __init__(self, data: ClipboardData | None = ..., max_size: int = ...) -> None:
        ...
    
    def set_data(self, data: ClipboardData) -> None:
        ...
    
    def get_data(self) -> ClipboardData:
        ...
    
    def rotate(self) -> None:
        ...
    


