[bot]
# 这里是 KafuBot 自身的配置
event_queue_size=100
nodes = []
node_dirs = ["./example/nodes"]
adapters = ["sekaibot.adapter.cqhttp"]
adapter_max_retries = 3


[bot.log]
# 这里是 KafuBot 自身日志相关的配置
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
# 这里是 CQHTTP 适配器的配置
adapter_type = "reverse-ws"
host = "127.0.0.1"
port = 8080
url = "/cqhttp/ws"
api_timeout=10

[permission]
superusers = ["2682064633", "3613158872", "2641460187", "group_596488203", "group_1011357049"]