"""
This type stub file was generated by pyright.
"""

import logging
from typing import TYPE_CHECKING
from typing_extensions import override
from structlog.typing import FilteringBoundLogger

"""SekaiBot 日志模块，基于 structlog。

使用 [`structlog`][structlog] 记录日志信息，支持日志级别过滤、详细信息开关等。

[structlog]: https://www.structlog.org/en/stable/
"""
if TYPE_CHECKING:
    ...
def configure_logging(level: str | int = ..., verbose_exception: bool = ...) -> None:
    """配置 structlog 日志系统。

    Args:
        level (str | int): 日志级别，如 `"INFO"`, `"DEBUG"` 或 数值 `10, 20, 30...`
        verbose_exception (bool): 是否记录详细异常信息。
    """
    ...

default_format = ...
class StructLogHandler(logging.Handler):
    """Python `logging` 日志 to `structlog` 适配器，将 `logging` 事件转发到 `structlog`。"""
    @override
    def emit(self, record: logging.LogRecord) -> None:
        ...
    


logger: FilteringBoundLogger = ...
