"""
This type stub file was generated by pyright.
"""

from typing import Generic, TYPE_CHECKING, final
from sekaibot.typing import ConfigT
from sekaibot.bot import Bot

"""SekaiBot 插件。

所有 SekaiBot 插件的基类。所有用户编写的插件必须继承自 `Plugin` 类。
"""
if TYPE_CHECKING:
    ...
__all__ = ["Plugin"]
class Plugin(Generic[ConfigT]):
    """SekaiBot 通用基类。

    Attributes:
        name: 类的名称。
        bot: 当前的机器人对象。
    """
    name: str
    bot: Bot
    Config: type[ConfigT]
    def __init__(self, bot: Bot) -> None:
        """初始化。

        Args:
            bot: 当前机器人对象。
        """
        ...
    
    @final
    @property
    def config(self) -> ConfigT:
        """类配置。"""
        ...
    


