"""
This type stub file was generated by pyright.
"""

from traitlets.config.configurable import SingletonConfigurable
from traitlets import Bool, Dict, Instance, Set, TraitError, Unicode

"""Configurable for configuring the IPython inline backend

This module does not import anything from matplotlib.
"""
def pil_available(): # -> bool:
    """Test if PIL/Pillow is available"""
    ...

class InlineBackendConfig(SingletonConfigurable):
    ...


class InlineBackend(InlineBackendConfig):
    """An object to store configuration of the inline backend."""
    rc = ...
    figure_formats = ...
    figure_format = ...
    print_figure_kwargs = ...
    _print_figure_kwargs_changed = ...
    close_figures = ...
    shell = ...


