"""
This type stub file was generated by pyright.
"""

import operator
from itertools import chain, groupby, zip_longest
from . import attributes, exc as orm_exc, loading, sync
from .base import state_str
from .. import exc as sa_exc, future, sql, util
from ..engine import cursor as _cursor
from ..sql import operators
from ..sql.elements import BooleanClauseList
from ..sql.selectable import LABEL_STYLE_TABLENAME_PLUS_COL

"""private module containing functions used to emit INSERT, UPDATE
and DELETE statements on behalf of a :class:`_orm.Mapper` and its descending
mappers.

The functions here are called only by the unit of work functions
in unitofwork.py.

"""
def save_obj(base_mapper, states, uowtransaction, single=...): # -> None:
    """Issue ``INSERT`` and/or ``UPDATE`` statements for a list
    of objects.

    This is called within the context of a UOWTransaction during a
    flush operation, given a list of states to be flushed.  The
    base mapper in an inheritance hierarchy handles the inserts/
    updates for all descendant mappers.

    """
    ...

def post_update(base_mapper, states, uowtransaction, post_update_cols): # -> None:
    """Issue UPDATE statements on behalf of a relationship() which
    specifies post_update.

    """
    ...

def delete_obj(base_mapper, states, uowtransaction): # -> None:
    """Issue ``DELETE`` statements for a list of objects.

    This is called within the context of a UOWTransaction during a
    flush operation.

    """
    ...

