"""
This type stub file was generated by pyright.
"""

from apscheduler.jobstores.base import BaseJobStore

class MemoryJobStore(BaseJobStore):
    """
    Stores jobs in an array in RAM. Provides no persistence support.

    Plugin alias: ``memory``
    """
    def __init__(self) -> None:
        ...
    
    def lookup_job(self, job_id):
        ...
    
    def get_due_jobs(self, now): # -> list[Any]:
        ...
    
    def get_next_run_time(self): # -> None:
        ...
    
    def get_all_jobs(self): # -> list[Any]:
        ...
    
    def add_job(self, job): # -> None:
        ...
    
    def update_job(self, job): # -> None:
        ...
    
    def remove_job(self, job_id): # -> None:
        ...
    
    def remove_all_jobs(self): # -> None:
        ...
    
    def shutdown(self): # -> None:
        ...
    


