"""
This type stub file was generated by pyright.
"""

class KnownIssue(Exception):
    """
    Raised in case of an known problem. Mostly because of cpython bugs.
    Executing.node gets set to None in this case.
    """
    ...


class VerifierFailure(Exception):
    """
    Thrown for an unexpected mapping from instruction to ast node
    Executing.node gets set to None in this case.
    """
    def __init__(self, title: object, node: object, instruction: object) -> None:
        ...
    


