"""
This type stub file was generated by pyright.
"""

import errno
import sys
import pickle
from typing import Any

"""
This module is here to ensure compatibility of Windows/Linux/MacOS and
different Python versions.
"""
class Unpickler(pickle.Unpickler):
    def find_class(self, module: str, name: str) -> Any:
        ...
    


def pickle_load(file): # -> Any:
    ...

def pickle_dump(data, file, protocol): # -> None:
    ...

