"""
This type stub file was generated by pyright.
"""

import types
from jedi import debug

"""
A static version of getattr.
This is a backport of the Python 3 code with a little bit of additional
information returned to enable Jedi to make decisions.
"""
_sentinel = ...
def getattr_static(obj, attr, default=...): # -> tuple[Any | object, Literal[True]] | tuple[Any | object, Literal[False]] | tuple[Any | object, bool] | tuple[Any, Literal[False]] | tuple[object, Literal[False]]:
    """Retrieve attributes without triggering dynamic lookup via the
       descriptor protocol,  __getattr__ or __getattribute__.

       Note: this function may not be able to retrieve all attributes
       that getattr can fetch (like dynamically created attributes)
       and may find attributes that getattr can't (like descriptors
       that raise AttributeError). It can also return descriptor objects
       instead of instance members in some cases. See the
       documentation for details.

       Returns a tuple `(attr, is_get_descriptor)`. is_get_descripter means that
       the attribute is a descriptor that has a `__get__` attribute.
    """
    ...

