"""
This type stub file was generated by pyright.
"""

import os
from jedi.api import classes
from jedi.api.strings import StringName, get_quote_ending
from jedi.api.helpers import match
from jedi.inference.helpers import get_str_or_none

class PathName(StringName):
    api_type = ...


def complete_file_name(inference_state, module_context, start_leaf, quote, string, like_name, signatures_callback, code_lines, position, fuzzy): # -> Generator[Completion, Any, None]:
    ...

