"""
This type stub file was generated by pyright.
"""

def indent(func): # -> Callable[..., Indent]:
    """
    Decorator for allowing to use method as normal method or with
    context manager for auto-indenting code blocks.
    """
    ...

class Indent:
    def __init__(self, instance, line) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, type_, value, traceback): # -> None:
        ...
    


