"""
This type stub file was generated by pyright.
"""

from jedi.inference.base_value import ValueSet, ValueWrapper

'''
Decorators are not really values, however we need some wrappers to improve
docstrings and other things around decorators.
'''
class Decoratee(ValueWrapper):
    def __init__(self, wrapped_value, original_value) -> None:
        ...
    
    def py__doc__(self):
        ...
    
    def py__get__(self, instance, class_value): # -> ValueSet:
        ...
    
    def get_signatures(self): # -> list[Any]:
        ...
    


