"""
This type stub file was generated by pyright.
"""

import enum
import os
import struct
from typing import IO

"""
ELF file parser.

This provides a class ``ELFFile`` that parses an ELF executable in a similar
interface to ``ZipFile``. Only the read interface is implemented.

Based on: https://gist.github.com/lyssdod/f51579ae8d93c8657a5564aefc2ffbca
ELF header: https://refspecs.linuxfoundation.org/elf/gabi4+/ch4.eheader.html
"""
class ELFInvalid(ValueError):
    ...


class EIClass(enum.IntEnum):
    C32 = ...
    C64 = ...


class EIData(enum.IntEnum):
    Lsb = ...
    Msb = ...


class EMachine(enum.IntEnum):
    I386 = ...
    S390 = ...
    Arm = ...
    X8664 = ...
    AArc64 = ...


class ELFFile:
    """
    Representation of an ELF executable.
    """
    def __init__(self, f: IO[bytes]) -> None:
        ...
    
    @property
    def interpreter(self) -> str | None:
        """
        The path recorded in the ``PT_INTERP`` section header.
        """
        ...
    


