"""
This type stub file was generated by pyright.
"""

from textwrap import dedent
from parso import split_lines
from jedi import debug
from jedi.api.exceptions import RefactoringError
from jedi.api.refactoring import EXPRESSION_PARTS, Refactoring
from jedi.common import indent_block
from jedi.parser_utils import function_is_classmethod, function_is_staticmethod

_DEFINITION_SCOPES = ...
_VARIABLE_EXCTRACTABLE = ...
def extract_variable(inference_state, path, module_node, name, pos, until_pos): # -> Refactoring:
    ...

def extract_function(inference_state, path, module_context, name, pos, until_pos): # -> Refactoring:
    ...

