"""
This type stub file was generated by pyright.
"""

import errno
import os
import sys
from contextlib import contextmanager
from typing import IO, Iterator, TextIO

__all__ = ["flush_stdout"]
def flush_stdout(stdout: TextIO, data: str) -> None:
    ...

