"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Type
from .. import util
from ..engine.interfaces import Dialect

if TYPE_CHECKING:
    ...
__all__ = ("mssql", "mysql", "oracle", "postgresql", "sqlite")
registry = ...
plugins = ...
