"""
This type stub file was generated by pyright.
"""

import os
import sys
from collections import deque
from io import StringIO
from typing import Optional

"""A lexical analyzer class for simple shell-like syntaxes."""
class shlex:
    "A lexical analyzer class for simple shell-like syntaxes."
    def __init__(self, instream=..., infile=..., posix=..., punctuation_chars=...) -> None:
        ...
    
    def push_token(self, tok): # -> None:
        "Push a token onto the stack popped by the get_token method"
        ...
    
    def push_source(self, newstream, newfile=...): # -> None:
        "Push an input source onto the lexer's input source stack."
        ...
    
    def pop_source(self): # -> None:
        "Pop the input source stack."
        ...
    
    def get_token(self): # -> str | None:
        "Get a token from the input stream (or from stack if it's nonempty)"
        ...
    
    def read_token(self): # -> str | None:
        ...
    
    def sourcehook(self, newfile): # -> tuple[str | Any, TextIOWrapper[_WrappedBuffer]]:
        "Hook called on a filename to be sourced."
        ...
    
    def error_leader(self, infile=..., lineno=...): # -> str:
        "Emit a C-compiler-like, Emacs-friendly error-message leader."
        ...
    
    def __iter__(self): # -> Self:
        ...
    
    def __next__(self): # -> str | None:
        ...
    
    next = ...


