"""
This type stub file was generated by pyright.
"""

import enum
from typing import Final, final

__all__ = ["_CopyMode", "_NoValue"]
@final
class _CopyMode(enum.Enum):
    ALWAYS = ...
    IF_NEEDED = ...
    NEVER = ...


@final
class _NoValueType:
    ...


_NoValue: Final[_NoValueType] = ...
