"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from prompt_toolkit.styles.pygments import pygments_token_to_classname
from .base import StyleAndTextTuples
from pygments.token import Token

if TYPE_CHECKING:
    ...
__all__ = ["PygmentsTokens"]
class PygmentsTokens:
    """
    Turn a pygments token list into a list of prompt_toolkit text fragments
    (``(style_str, text)`` tuples).
    """
    def __init__(self, token_list: list[tuple[Token, str]]) -> None:
        ...
    
    def __pt_formatted_text__(self) -> StyleAndTextTuples:
        ...
    


