"""
This type stub file was generated by pyright.
"""

"""
Exports function list_versions() for unicode version level support.

This code generated by wcwidth/bin/update-tables.py on 2023-09-14 15:45:33 UTC.
"""
def list_versions(): # -> tuple[Literal['4.1.0'], Literal['5.0.0'], Literal['5.1.0'], Literal['5.2.0'], Literal['6.0.0'], Literal['6.1.0'], Literal['6.2.0'], Literal['6.3.0'], Literal['7.0.0'], Literal['8.0.0'], Literal['9.0.0'], Literal['10.0.0'], Literal['11.0.0'], Literal['12.0.0'], Literal['12.1.0'], Literal['13.0.0'], Literal['14.0.0'], Literal['15.0.0'], Literal['15.1.0']]:
    """
    Return Unicode version levels supported by this module release.

    Any of the version strings returned may be used as keyword argument
    ``unicode_version`` to the ``wcwidth()`` family of functions.

    :returns: Supported Unicode version numbers in ascending sorted order.
    :rtype: list[str]
    """
    ...

