"""
This type stub file was generated by pyright.
"""

import unicodedata
import pygments.lexers as pygments_lexers
import os
import sys
import traceback
from wcwidth import wcwidth
from IPython.core.completer import _deduplicate_completions, cursor_to_position, provisionalcompleter
from prompt_toolkit.completion import Completer, Completion
from prompt_toolkit.lexers import Lexer, PygmentsLexer
from prompt_toolkit.patch_stdout import patch_stdout

"""prompt-toolkit utilities

Everything in this module is a private API,
not to be used outside IPython.
"""
_completion_sentinel = ...
class IPythonPTCompleter(Completer):
    """Adaptor to provide IPython completions to prompt_toolkit"""
    def __init__(self, ipy_completer=..., shell=...) -> None:
        ...
    
    @property
    def ipy_completer(self):
        ...
    
    def get_completions(self, document, complete_event): # -> Generator[Completion, Any, None]:
        ...
    


class IPythonPTLexer(Lexer):
    """
    Wrapper around PythonLexer and BashLexer.
    """
    def __init__(self) -> None:
        ...
    
    def lex_document(self, document): # -> Callable[[int], StyleAndTextTuples]:
        ...
    


