[project]
name = "sekaibot-adapter-onebot"
version = "0.1.0"
description = "OneBot V12 adapter for SekaiBot."
authors = [
    {name = "Kotodama",email = "2682064633@qq.com"}
]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "qq", "qqbot", "cqhttp", "coolq"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.11,<4"
dependencies = ["sekaibot==0.1.0"]

[project.urls]
Repository = "https://github.com/sekaibot-dev/sekaibot"

[tool.uv.sources]
alicebot = { workspace = true }

[tool.hatch.build]
packages = ["sekaibot"]
exclude = ["sekaibot/__init__.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"