"""
This type stub file was generated by pyright.
"""

"""
Vi Digraphs.
This is a list of special characters that can be inserted in Vi insert mode by
pressing Control-K followed by to normal characters.

Taken from Neovim and translated to Python:
https://raw.githubusercontent.com/neovim/neovim/master/src/nvim/digraph.c
"""
__all__ = ["DIGRAPHS"]
DIGRAPHS: dict[tuple[str, str], int] = ...
