"""
This type stub file was generated by pyright.
"""

from inspect import Parameter
from parso import tree
from jedi.inference.utils import to_list
from jedi.inference.names import ParamNameWrapper
from jedi.inference.helpers import is_big_annoying_library

"""
This module is responsible for inferring *args and **kwargs for signatures.

This means for example in this case::

    def foo(a, b, c): ...

    def bar(*args):
        return foo(1, *args)

The signature here for bar should be `bar(b, c)` instead of bar(*args).
"""
@to_list
def process_params(param_names, star_count=...):
    ...

class ParamNameFixedKind(ParamNameWrapper):
    def __init__(self, param_name, new_kind) -> None:
        ...
    
    def get_kind(self): # -> Any:
        ...
    


