"""
This type stub file was generated by pyright.
"""

from apscheduler.executors.base import BaseExecutor

class AsyncIOExecutor(BaseExecutor):
    """
    Runs jobs in the default executor of the event loop.

    If the job function is a native coroutine function, it is scheduled to be run directly in the
    event loop as soon as possible. All other functions are run in the event loop's default
    executor which is usually a thread pool.

    Plugin alias: ``asyncio``
    """
    def start(self, scheduler, alias): # -> None:
        ...
    
    def shutdown(self, wait=...): # -> None:
        ...
    


