"""
This type stub file was generated by pyright.
"""

from typing import Iterator, List, Optional, Tuple
from parso.python.tokenize import tokenize
from parso.utils import parse_version_string
from parso.python.token import PythonTokenTypes

class NFAArc:
    def __init__(self, next_: NFAState, nonterminal_or_string: Optional[str]) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class NFAState:
    def __init__(self, from_rule: str) -> None:
        ...
    
    def add_arc(self, next_, nonterminal_or_string=...): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class GrammarParser:
    """
    The parser for Python grammar files.
    """
    def __init__(self, bnf_grammar: str) -> None:
        ...
    
    def parse(self) -> Iterator[Tuple[NFAState, NFAState]]:
        ...
    


