"""
This type stub file was generated by pyright.
"""

from shlex import quote

bashcode = ...
tcshcode = ...
fishcode = ...
powershell_code = ...
shell_codes = ...
def shellcode(executables, use_defaults=..., shell=..., complete_arguments=..., argcomplete_script=...): # -> str:
    """
    Provide the shell code required to register a python executable for use with the argcomplete module.

    :param list(str) executables: Executables to be completed (when invoked exactly with this name)
    :param bool use_defaults: Whether to fallback to readline's default completion when no matches are generated
        (affects bash only)
    :param str shell: Name of the shell to output code for
    :param complete_arguments: Arguments to call complete with (affects bash only)
    :type complete_arguments: list(str) or None
    :param argcomplete_script: Script to call complete with, if not the executable to complete.
        If supplied, will be used to complete *all* passed executables.
    :type argcomplete_script: str or None
    """
    ...

