"""
This type stub file was generated by pyright.
"""

class SchedulerAlreadyRunningError(Exception):
    """Raised when attempting to start or configure the scheduler when it's already running."""
    def __str__(self) -> str:
        ...
    


class SchedulerNotRunningError(Exception):
    """Raised when attempting to shutdown the scheduler when it's not running."""
    def __str__(self) -> str:
        ...
    


