"""
This type stub file was generated by pyright.
"""

from apscheduler.schedulers.base import BaseScheduler

def run_in_event_loop(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], None]:
    ...

class AsyncIOScheduler(BaseScheduler):
    """
    A scheduler that runs on an asyncio (:pep:`3156`) event loop.

    The default executor can run jobs based on native coroutines (``async def``).

    Extra options:

    ============== =============================================================
    ``event_loop`` AsyncIO event loop to use (defaults to the global event loop)
    ============== =============================================================
    """
    _eventloop = ...
    _timeout = ...
    def start(self, paused=...): # -> None:
        ...
    
    @run_in_event_loop
    def shutdown(self, wait=...): # -> None:
        ...
    
    @run_in_event_loop
    def wakeup(self): # -> None:
        ...
    


