"""
This type stub file was generated by pyright.
"""

from ..engine import Connection as Connection, Engine as Engine, create_engine as create_engine

"""2.0 API features.

this module is legacy as 2.0 APIs are now standard.

"""
