"""
This type stub file was generated by pyright.
"""

import sys
from contextlib import AbstractContextManager
from types import TracebackType
from typing import Optional, TYPE_CHECKING, Type, cast

if sys.version_info < (3, 11):
    ...
if TYPE_CHECKING:
    BaseClass = AbstractContextManager[None]
else:
    ...
class suppress(BaseClass):
    """Backport of :class:`contextlib.suppress` from Python 3.12.1."""
    def __init__(self, *exceptions: type[BaseException]) -> None:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, exctype: Optional[Type[BaseException]], excinst: Optional[BaseException], exctb: Optional[TracebackType]) -> bool:
        ...
    


