name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install black ruff mypy pylint pytest coverage

    - name: Run black (code style)
      run: black --check .

    - name: Run ruff (linter)
      run: ruff .

    - name: Run mypy (type checker)
      run: mypy sekaibot/

    - name: Run pylint
      run: pylint sekaibot/

    - name: Run pytest with coverage
      run: |
        pytest --cov=sekaibot
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
